site_name: DIGITbrain Documentation
repo_url: https://github.com/digitbrain/metadata
edit_uri: edit/main/docs
theme:
  name: material
  logo: img/db-logo.png
  favicon: img/db-logo.png
  palette:
    primary: teal
    accent: cyan
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: index.md
  - Getting Started:
      - Getting Started: start/index.md
      - Microservice: start/microservice.md
      - Algorithm: start/algorithm.md
      - Model: start/model.md
      - Data: start/data.md
      - MA Pair: start/ma_pair.md
      - DMA Tuple:
          - DMA Tuple: start/dma_tuple/index.md
          - Data Assets Mapping: start/dataassetsmapping.md
          - Deployment: start/deployment.md
      - Supporting Metadata: start/supporting_metadata.md
  - Going Further:
      - Going Further: adv/index.md
      - Open Parameters: adv/params.md
      - Exposing Microservices: adv/expose.md
      - Dynamic Domains: adv/domains.md
      - Enabling HTTPS: adv/https.md
      - Edge Devices: adv/edge.md
  - Asset Detail:
      - Asset Detail: attributes/index.md
      - Microservice:
          - Microservice: attributes/microservice/index.md
          - Configuration Data: attributes/configurationdata.md
          - Data Resources: attributes/data_resources.md
          - Parameters: attributes/parameters.md
          - Metrics: attributes/metrics.md
      - Algorithm:
          - Algorithm: attributes/algorithm/index.md
      - Model:
          - Model: attributes/model/index.md
          - Slots: attributes/slots.md
      - Data:
          - Data: attributes/data/index.md
      - MA Pair:
          - MA Pair: attributes/ma_pair/index.md
      - DMA Tuple:
          - DMA Tuple: attributes/dma_tuple/index.md
          - Data Assets Mapping: attributes/dataassetsmapping.md
          - Deployment: attributes/deployment.md
      - Supporting Metadata: attributes/supporting_metadata.md
  - Asset Tables:
      - Asset Tables: tables/index.md
      - Microservice:
          - Microservice: tables/microservice/index.md
          - Configuration Data: tables/configurationdata.md
          - Data Resources: tables/data_resources.md
          - Parameters: tables/parameters.md
          - Metrics: tables/metrics.md
      - Algorithm:
          - Algorithm: tables/algorithm/index.md
      - Model:
          - Model: tables/model/index.md
          - Slots: tables/slots.md
      - Data:
          - Data: tables/data/index.md
      - MA Pair:
          - MA Pair: tables/ma_pair/index.md
      - DMA Tuple:
          - DMA Tuple: tables/dma_tuple/index.md
          - Data Assets Mapping: tables/dataassetsmapping.md
          - Deployment: tables/deployment.md
      - Supporting Metadata: tables/supporting_metadata.md
  - Examples:
      - Examples: examples/index.md
      - Fraunhofer: examples/Fraunhofer.md
      - ITAINNOVA: examples/ITAINNOVA.md
      - DFKI: examples/DFKI.md
      - CoSimulation: examples/Cosimulation.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
