author:
  description: Created by
  example: '"Jay"'
  type: String
cloud_config:
  description: cloud-init - https://cloudinit.readthedocs.io/ - configuration for
    contextualisation of the VM
  example: "{\n              \"runcmd\": [\"echo one\", \"echo two\"]\n            }"
  type: Map
cloudbroker:
  description: Configuration data for a CloudBroker instance
  type: Map[String, String]
date:
  description: Created on
  example: 18.08.2022
  type: Date
deployment_id:
  description: ID of CloudBroker Deployment
  example: '"16b1e2d4-3a2c-406e-8c45-5637099021f0"'
  type: UUID
domain_name:
  description: 'Subdomain (on cbp-routing.ch) to create and attach to this instance
    using dynamic DNS. For the given example, the following domain will be assigned
    to the instance: mysubdomain.cbp-routing.ch'
  example: '"mysubdomain"'
  type: String
domain_names:
  description: ID of a CloudBroker Domain Name for this instance
  example: '["om207925-b52a-4697-b2c3-563702208h9"]'
  type: List of UUIDs
edge:
  description: Connection data for a bring-your-own edge
  type: Map[String, String]
endpoint:
  description: accesible IP or FQDN of edge device
  example: '"https://cloudsme-cbp.scaletools.com.ua"'
  type: URL
id:
  description: DIGITbrain reference
  example: '"HOSTID_MYHOST_A"'
  type: UUID
instance_type_id:
  description: ID of CloudBroker InstanceType
  example: '"ca727925-a5ca-4697-b2c3-8788d82457d5"'
  type: UUID
key_pair_id:
  description: ID of CloudBroker Key Pair
  example: '"ap207925-a5ca-4697-b2c3-5637099021f0"'
  type: UUID
name:
  description: Short name for the node/device
  example: '"Ubuntu small"'
  type: String
opened_port:
  description: Ports to open at cloud side
  example: '"80,443,8080,30010"'
  type: String (comma separated integers)
ssh_private_key:
  description: private key for SSH connection.
  example: '"-----BEGIN RSA PRIVATE KEY----- MIIEowIBAAKCAQEApwn..."'
  type: String
ssh_username:
  description: username for SSH connection. Defaults to ubuntu
  example: '"ubuntu"'
  type: String
type:
  description: computing centre
  example: '"cloudbroker"'
  type: Enumeration ["cloudbroker", "edge"]
