# This is a basic workflow to help you get started with Actions

name: Generate docs and publish

on:
  # Triggers the workflow on push events for main and any fix/* feat/* branches
  push:
    branches:
      - main
      - "*/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    name: Generate docs from Excel
    runs-on: ubuntu-latest

    # Define outputs for the auto-commit step
    outputs:
      changed: ${{ steps.auto_commit.outputs.changes_detected }}
      commit: ${{ steps.auto_commit.outputs.commit_hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pandas openpyxl tabulate jinja2

      - name: Run xls2md (generate Markdown tables)
        run: python tools/xls2md.py

      - name: Run xls2mkdocs (generate fields listing)
        run: python tools/xls2mkdocs.py

      - name: Run example2md (generate tables for examples)
        run: python tools/example2md.py

      - name: Commit any changes made by xls2md/xls2mkdocs
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: ${{ github.event.head_commit.message }} [AUTO]
          file_pattern: docs/*/*.md docs/*/*/*.md

  publish:
    name: Publish the site
    runs-on: ubuntu-latest
    needs: generate
    if: |
      github.repository == 'DIGITbrain/digitbrain.github.io' &&
      github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository using auto-commit
        if: needs.generate.outputs.changed == 'true'
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.generate.outputs.commit }}

      - name: Checkout repository normally
        if: needs.generate.outputs.changed == 'false'
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Mkdocs
        run: pip install jinja2==3.0.0 mkdocs-material

      - name: Run Mkdocs deploy
        run: mkdocs gh-deploy --force
