# This is a basic workflow to help you get started with Actions

name: Publish site


on:
  release:
    types: [published]


jobs:

  publish:
    name: Publish the site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository normally
        if: needs.generate.outputs.changed == 'false'
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Mkdocs
        run: pip install mkdocs-material==9.1.4 swagger-markdown==0.9.16

      - name: Run Mkdocs deploy
        run: mkdocs gh-deploy --force
